  pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                echo 'scm git'
                git branch: 'main', url: 'https://github.com/sivalakshmanna/gcp-cloudrun-storage.git'
            }
        }
        
       
        stage('Build docker image'){
            steps{
                script{
                    echo 'docker image build'
		    	
	            sh 'docker build -t sivalakshmanna/siva:${BUILD_NUMBER} .'
                }
            }
        }		
        		
	    stage('Push image to Hub'){
            steps{
                   
		   script {
                         withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                             sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                             sh 'docker push sivalakshmanna/siva:${BUILD_NUMBER}'
                         } 
                }
            }
        
		
      
    }
   
}
